apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-demo
  name: java-demo
  namespace: default
spec:
  ports:
    - name: http
      port: 8086
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-demo
  type: ClusterIP
