kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    #extraMounts:
    #  - containerPath: /etc/docker/certs.d/192.168.71.181
    #    hostPath: /Users/timxia/project/demo/ssl
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8070
        protocol: TCP
      - containerPort: 443
        hostPort: 7443
        protocol: TCP
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
     config_path = "/etc/containerd/certs.d"